on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
       # Deploy ARM template
       
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
          
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: "e0f25586-2494-41ef-b304-ef8ae650e205"
          resourceGroupName: "rg-kamesh-c-001"
          template: stgacc/storage_account.json
          parameters: "deploymentprefix=start"
